-- Firebird schema install (tables owned by the connecting user; no schema prefix)
-- Requires Firebird 3.0+ (GENERATED BY DEFAULT AS IDENTITY).
-- Uses plain TIMESTAMP (not TIMESTAMP WITH TIME ZONE) — avoids provider timezone-binding
-- issues with FirebirdSql.Data.FirebirdClient 10.x. All timestamps are UTC by convention.
-- IF NOT EXISTS is NOT used because the database is freshly created per test run.
CREATE TABLE "Schema" (
    "Version" INTEGER NOT NULL,
    CONSTRAINT "PK_HangFire_Schema" PRIMARY KEY ("Version"));
CREATE TABLE "Job" (
    "Id"             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "StateId"        BIGINT,
    "StateName"      VARCHAR(20),
    "InvocationData" BLOB SUB_TYPE TEXT NOT NULL,
    "Arguments"      BLOB SUB_TYPE TEXT NOT NULL,
    "CreatedAt"      TIMESTAMP NOT NULL,
    "ExpireAt"       TIMESTAMP,
    CONSTRAINT "PK_HangFire_Job" PRIMARY KEY ("Id"));
CREATE TABLE "State" (
    "Id"        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "JobId"     BIGINT NOT NULL,
    "Name"      VARCHAR(20) NOT NULL,
    "Reason"    VARCHAR(100),
    "CreatedAt" TIMESTAMP NOT NULL,
    "Data"      BLOB SUB_TYPE TEXT,
    CONSTRAINT "PK_HangFire_State" PRIMARY KEY ("Id"));
CREATE TABLE "JobParameter" (
    "JobId" BIGINT NOT NULL,
    "Name"  VARCHAR(40) NOT NULL,
    "Value" BLOB SUB_TYPE TEXT,
    CONSTRAINT "PK_HangFire_JobParameter" PRIMARY KEY ("JobId", "Name"));
CREATE TABLE "JobQueue" (
    "Id"        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "JobId"     BIGINT NOT NULL,
    "Queue"     VARCHAR(50) NOT NULL,
    "FetchedAt" TIMESTAMP,
    CONSTRAINT "PK_HangFire_JobQueue" PRIMARY KEY ("Id"));
CREATE TABLE "Server" (
    "Id"            VARCHAR(200) NOT NULL,
    "Data"          BLOB SUB_TYPE TEXT,
    "LastHeartbeat" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_HangFire_Server" PRIMARY KEY ("Id"));
CREATE TABLE "Hash" (
    "Key"      VARCHAR(100) NOT NULL,
    "Field"    VARCHAR(100) NOT NULL,
    "Value"    BLOB SUB_TYPE TEXT,
    "ExpireAt" TIMESTAMP,
    CONSTRAINT "PK_HangFire_Hash" PRIMARY KEY ("Key", "Field"));
CREATE TABLE "List" (
    "Id"       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Key"      VARCHAR(100) NOT NULL,
    "Value"    BLOB SUB_TYPE TEXT,
    "ExpireAt" TIMESTAMP,
    CONSTRAINT "PK_HangFire_List" PRIMARY KEY ("Id"));
-- Firebird 4.x: UTF8 index = 4 bytes/char; 4 KB page allows ~1024 bytes total composite key.
-- VARCHAR(100)+VARCHAR(100) = 800 bytes, fits; VARCHAR(100)+VARCHAR(256) = 1424, exceeds limit.
CREATE TABLE "Set" (
    "Key"      VARCHAR(100) NOT NULL,
    "Value"    VARCHAR(100) NOT NULL,
    "Score"    DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    "ExpireAt" TIMESTAMP,
    CONSTRAINT "PK_HangFire_Set" PRIMARY KEY ("Key", "Value"));
CREATE TABLE "Counter" (
    "Id"       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Key"      VARCHAR(100) NOT NULL,
    "Value"    INTEGER NOT NULL,
    "ExpireAt" TIMESTAMP,
    CONSTRAINT "PK_HangFire_Counter" PRIMARY KEY ("Id"));
CREATE TABLE "AggregatedCounter" (
    "Key"      VARCHAR(100) NOT NULL,
    "Value"    BIGINT DEFAULT 0 NOT NULL,
    "ExpireAt" TIMESTAMP,
    CONSTRAINT "PK_HangFire_AggregatedCounter" PRIMARY KEY ("Key"));
CREATE TABLE "hf_lock" (
    "resource"   VARCHAR(100) NOT NULL,
    "owner_id"   VARCHAR(40) NOT NULL,
    "expires_at" TIMESTAMP NOT NULL,
    "version"    INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT "PK_HangFire_hf_lock" PRIMARY KEY ("resource"));
MERGE INTO "Schema" target USING (SELECT 10 AS V FROM RDB$DATABASE) src ON (target."Version" = src.V) WHEN NOT MATCHED THEN INSERT ("Version") VALUES (src.V);
